### ISSUE TITLE
Suggestion: "Let's Do" Mods

### ISSUE THREAD

**Issue by tubBandit** [xanthian/variantcomposters#2]
Hey! Great mod, would love to have compatibility for the "Let's Do" mods series by satisfy. TIA
[link to projects] [https://www.curseforge.com/members/satisfy/projects](https://www.curseforge.com/members/satisfy/projects)

**Comment by xanthian** [comment]
Vinery and Beach Party are already supported..
Which others add a plank style

> Hey! Great mod, would love to have compatibility for the "Let's Do" mods series by satisfy. TIA [link to projects] https://www.curseforge.com/members/satisfy/projects

**Comment by tubBandit** [comment]
Sorry, I should be more specific. The composters are not composting things like lettuce and the seeds from those mods.

**Comment by xanthian** [comment]
working fine in testing lettuce seeds from Lets Do 'Candlelight'

![image](https://github.com/xanthian/variantcomposters/assets/7688001/31bcb13d-d89a-4233-b4b6-3667f2db75e0)

**Comment by tubBandit** [comment]
hmm is that forge or fabric? I am running the latest fabric versions and it doesn't seem to want to accept them.

**Comment by xanthian** [comment]
Fabric
what other mods do you have? could be something conflicting

**Comment by tubBandit** [comment]
Sat down and did more testing, must have been fixed recently... That's embarrassing XD
I was running Fabric 1.20.1 with v- composters v. 2.3 but in v. 2.4 the crops seem to compost properly.
Will close.l Thank you so much for being quick to respond!
